### ISSUE TITLE
Legal page

### ISSUE THREAD

**Issue by henhuy** [rl-institut/E_Metrobus#10]
Set up legal page

TODOS:

- [ ] Text
- [x] Layout
- [ ] Link on menu

**Comment by bmlancien** [comment]
@mdrli The layout should be scrollable. We do not have the content right now, but this will probably be composed of partner logos and text. We can add a placeholder at the moment and we will change it when we get the content. The menu will also be added later.

**Comment by bmlancien** [comment]
Wait until we get more infos from the BVG about what to put in there
