### ISSUE TITLE
Comparison chart number explanation missing

### ISSUE THREAD

**Issue by henhuy** [rl-institut/E_Metrobus#110]
Implement dropdown menu "Woher kommen diese Zahlen?" (from comparison page concept)

**Comment by henhuy** [comment]
Shall we implement it?
What info shall be shown?

**Comment by bmlancien** [comment]
I'm not sure anymore about that. We can ask this during our next meeting with Tim.

**Comment by henhuy** [comment]
Duplicate of #139
