### ISSUE TITLE
The info-page looks overloaded

### ISSUE THREAD

**Issue by bmlancien** [rl-institut/E_Metrobus#119]
Use accordion to separate each section

**Comment by mdrli** [comment]
I have pushed it on the info_page branch. Does it look okay? What should I change?
Also there is a problem when you open one accordion all of them open at once, I don't know how to fix it, @henhuy maybe you have an idea?

**Comment by bmlancien** [comment]
@mdrli I think this is due to a wrong accordion structure. For example, `data-accordion-item` is now set in the code on the accordion div. This attribute should be on the individual items of the accordion though.

Can you also remove the margins? The accordion should take the whole width and touch the top-navigation.

**Comment by mdrli** [comment]
@bmlancien Okay I tried it. Now it should work.

**Comment by bmlancien** [comment]
Looks good! Thank you
