### ISSUE TITLE
The user doesn't know how many questions she already answered

### ISSUE THREAD

**Issue by bmlancien** [rl-institut/E_Metrobus#120]
On the question page, there should be an indication of the numbers of questions already answered in this specific category. 

Suggestion: Add blue bar below top navigation:

![Dashboard (5)](https://user-images.githubusercontent.com/33999424/76540397-61597480-6482-11ea-913c-715f4f7b31ef.png)

**Comment by mdrli** [comment]
I added a progress bar dummy on the branch process_bar, but I don't know how to get it to work properly. @henhuy could you do this?
