### ISSUE TITLE
Feedback page doesn't exist

### ISSUE THREAD

**Issue by bmlancien** [rl-institut/E_Metrobus#122]
Create feedback page including 3-4 questions for users. Add possibility to give stars and to write text (like Airbnb app)

- [x] Mockup
- [x] Implementation
- [ ] Redirect to feedback view after 2sec @ finished view
- [x] Implement stars as JS

**Comment by bmlancien** [comment]
![Rating (1)](https://user-images.githubusercontent.com/33999424/77564515-25cb9b00-6ec3-11ea-9618-2c32a2ab2f0f.png)

**Comment by bmlancien** [comment]
@henhuy How easy would it be to implement this?

I'm not sure how to link this page with the app. Maybe make it appear automatically 2-3 seconds after landing on the congratulation page.

**Comment by henhuy** [comment]
Should be easy. (If you can provide the "stars").

Maybe with a small button on congratulation page?

**Comment by bmlancien** [comment]
The problem is that there are already 2 buttons on that page. I would rather force it to pop up so that every user sees it (we are more interested in them giving us a feedback than them sharing the results with their friends) but with the "skip" option, of course. Skipping the rating process or finishing it, they would go back to the congratulations page.

I will make a static page with dummy text and stars.

**Comment by mdrli** [comment]
@bmlancien pushed it on feedback_page. It is okay?

**Comment by bmlancien** [comment]
@mdrli yes, thank you!
