### ISSUE TITLE
Change chart icons

### ISSUE THREAD

**Issue by henhuy** [rl-institut/E_Metrobus#135]
Hey @bmlancien ,

just saw that PR #125 does wanted to change chart icons too.
Which icons shall be replaced? (see chart below)

![grafik](https://user-images.githubusercontent.com/17476051/77763522-82ea5c80-703b-11ea-91fa-67f4a1e03d4b.png)

**Comment by henhuy** [comment]
or is everything fine here?

**Comment by bmlancien** [comment]
Yes, but just the e-bus icon. It should be the same as on the top-nav bar.

**Comment by henhuy** [comment]
Fixed it and pushed directly to dev...
