### ISSUE TITLE
Some icons on tap-nav are not displayed correctly

### ISSUE THREAD

**Issue by bmlancien** [rl-institut/E_Metrobus#138]
- [ ] Dashboard icon is not displayed
- [ ] "Ich" icon in question category is too large

![localhost_3000_dashboard_(iPhone 6_7_8) (3)](https://user-images.githubusercontent.com/33999424/78234035-ddba0300-74d6-11ea-8cc4-18cf4c57e3fa.png)

![localhost_3000_answer_(iPhone 6_7_8) (1)](https://user-images.githubusercontent.com/33999424/78234056-e4e11100-74d6-11ea-9f78-dcc8bb800a98.png)

**Comment by henhuy** [comment]
Hey @bmlancien , for me everything works fine...
Please check if error is on your side?
- icons present in staticfolder or missing?
- Maybe reload page and clear cache?

**Comment by bmlancien** [comment]
After clearing cache, the ICH icon works fine. The e-bus icon on dashboard is still missing though.

I have this path in the e-metro category (this one works fine)
`/static/images/icons/i_ebus_black_fill.svg`

but this one on the dashboard:
`/static/images/icons/Icon_E_Bus_Front.svg`

**Comment by henhuy** [comment]
You are right - I fixed it!
Icon was stored in my staticfolder...
