### ISSUE TITLE
New translations

### ISSUE THREAD

**Issue by henhuy** [rl-institut/E_Metrobus#155]

**Comment by henhuy** [comment]
Hey @ciaradunks ,

I updated translations in django.po file in new branch "new_translations".
Could you translate? Thanks!!

**Comment by ciaradunks** [comment]
@henhuy yes sure, is early next week fine? I'm off until Tuesday

**Comment by henhuy** [comment]
Hey @ciaradunks ,

no problem!! The next milestone is planned for 18. May - no hurries ;)
And thank you very much for contributing!
