### ISSUE TITLE
Share link on congrats page is not optimal

### ISSUE THREAD

**Issue by bmlancien** [rl-institut/E_Metrobus#198]
@henhuy when a user tap on the share button, he gets a text with a link. Would it be possible to have it copied to the clipboard instead? I don't know if it's possible to have such a function...

![Screenshot_2020-05-13-15-16-23-656_com android chrome](https://user-images.githubusercontent.com/33999424/81817383-efa6b100-952c-11ea-8b37-b80acfe367b6.jpg)

**Comment by henhuy** [comment]
See #179 
I added copy link there plus buttons.
