### ISSUE TITLE
Finished page not working

### ISSUE THREAD

**Issue by bmlancien** [rl-institut/E_Metrobus#209]
![localhost_3000_finished_(iPhone 5_SE)](https://user-images.githubusercontent.com/33999424/82028928-8478ee00-9696-11ea-84f1-993fae21a506.png)

**Comment by bmlancien** [comment]
I have the same issue on the dashboard now.

**Comment by henhuy** [comment]
jepp -it's new. Don't know why yet...

**Comment by henhuy** [comment]
I'm going to refactor finished page
