### ISSUE TITLE
Display route swiping?

### ISSUE THREAD

**Issue by henhuy** [rl-institut/E_Metrobus#214]
User Feedback: Is it possible to activate swiping on display route page?

**Comment by bmlancien** [comment]
I don't know how to do it and how easy it is to implement. You would probably have to help me on that one :)

**Comment by henhuy** [comment]
Maybe this:
https://get.foundation/sites/docs/javascript-utilities.html#touch

**Comment by henhuy** [comment]
I will try to implement it

**Comment by bmlancien** [comment]
It has been decided not to implement it
