### ISSUE TITLE
Privacy Popup 

### ISSUE THREAD

**Issue by henhuy** [rl-institut/E_Metrobus#260]
Add note that user privacy is assured

**Comment by henhuy** [comment]
Where? Landing page?

**Comment by bmlancien** [comment]
Yes, LP

**Comment by henhuy** [comment]
Can you start with a static design?
And I will add at-startup logic afterwards?

**Comment by bmlancien** [comment]
Alright

**Comment by bmlancien** [comment]
@henhuy I will ask someone to write the text. Just to be sure, we are not using cookies that the users should know about?

**Comment by henhuy** [comment]
yes! No user data stored
