### ISSUE TITLE
Add share icon to top nav

### ISSUE THREAD

**Issue by bmlancien** [rl-institut/E_Metrobus#278]
Remove star and points from top nav

![Dashboard (6)](https://user-images.githubusercontent.com/33999424/84286220-b4ed6400-ab3e-11ea-9d0b-efeaadbcc247.png)

**Comment by henhuy** [comment]
Instead of "Ergebnis teilen" button or additionally?

**Comment by bmlancien** [comment]
Yes, it should be for sharing the app, so basically send a link of the landing page, nothing to do with points. Maybe it was not clear with the mockup above, but the share icon should be there starting when the user arrives on the dashboard for the first time until offboarding. So, basically replacing the star and score.

**Comment by henhuy** [comment]
so no scores at all?
uff

**Comment by bmlancien** [comment]
On that top bar, no. But we might want to share scores on congrats page. We should have more feedback on that next week.
