### ISSUE TITLE
User-flow for non-bus users is missing

### ISSUE THREAD

**Issue by bmlancien** [rl-institut/E_Metrobus#316]
@henhuy Now we only have one user-flow (bus users):

Landing page -> onboarding -> single-page tour -> dashboard -> offboarding

It is thought for users that will be sitting inside the bus. But we also have to think about the users that will receive the app link from other users. Meaning that they probably won't be using a bus when receiving the link. In that case it doesn't make sense to ask them to select a route. But they still should be able to use the app. For them (non-bus users) the user-flow should be the following:

Landing page -> single-page tour -> dashboard -> offboarding

- The single-page tour wording should be slightly different.
- "My route" page should display a default route (but they still should be able to change the route if they want to).

What would be the best approach for implementing this? Using two different URLs?

**Comment by henhuy** [comment]
Yes, I think we should point non-bus-users to a different landing page, as current landing page text is "Toll, dass du mit einem E-Bus fährst". There should be a different text. Additionally, this would make it easier for me to distinguish non-bus users  and normal users and thus easier to define default route for the first ones...

**Comment by henhuy** [comment]
I will start adding a second landing page and default route implementation!
