### ISSUE TITLE
"Ich" category finished box is not centered

### ISSUE THREAD

**Issue by henhuy** [rl-institut/E_Metrobus#338]
Occurs only at "Ich" category?!

**Comment by bmlancien** [comment]
@henhuy Do you mean this? I've taken this screenshot from dev

![localhost_3000_finished_personal_(iPhone 6_7_8)](https://user-images.githubusercontent.com/33999424/86243686-184f3c80-bba7-11ea-95fd-eaf647700747.png)

**Comment by henhuy** [comment]
Yes!

**Comment by bmlancien** [comment]
Ah, I've just seen this on my smartphone, there is indeed a problem. On my local dev branch it is working fine...
