### ISSUE TITLE
Users are not able to see answered questions

### ISSUE THREAD

**Issue by bmlancien** [rl-institut/E_Metrobus#371]
Users should be able to go back to the questions categories and see selected, right and wrong answers. But they should not be able to answer the questions again.

- [ ] mockup @bmlancien 
- [ ] implementation @henhuy

**Comment by henhuy** [comment]
I thought we wouldn't do this in favor of showing wrong and correct answers?!

**Comment by bmlancien** [comment]
Exactly, the user would tap again on a category that was fully answered then he would go from question to question but only seeing right/wrong answers
