### ISSUE TITLE
Answer page should be removed

### ISSUE THREAD

**Issue by bmlancien** [rl-institut/E_Metrobus#372]
- The selected, right and wrong answers should be visible using different colors
- The answer page should be removed
- Instead there should be 2 options visible on the question page after answering :
  - Button "next question" -> next question
  - Button "learn more" -> dropdown full answer text

**Comment by henhuy** [comment]
I begin implementing functionality on question page!

**Comment by bmlancien** [comment]
This is how I imagine the flow:

Question view:

- One possible answer -> User taps his answer and goes directly to question answered view
- Multiple-choice -> User taps his answers and "Answer" button is displayed

![Question (2)](https://user-images.githubusercontent.com/33999424/86751935-4c12e200-c03f-11ea-82b5-857efb2e41bb.png)

Question answered view:

- Right answers will be green
- If a user has given a wrong answer it will be hightlighted in red

![Question_answered (1)](https://user-images.githubusercontent.com/33999424/86751882-43221080-c03f-11ea-9208-c4d6a04376d2.png)

**Comment by bmlancien** [comment]
It would be nice if on the question answered view the question flash gets a color (red if wrong, green if correct) (see second mockup from last comment)
