### ISSUE TITLE
Rename urls

### ISSUE THREAD

**Issue by henhuy** [rl-institut/E_Metrobus#397]
I think we could rename some urls:
- environment -> my_route
- questions_as_text -> summary
- legal -> infos
- display_route -> ?
- comparison -> ?
- dashboard -> quiz???

What do you think, @bmlancien ?

**Comment by bmlancien** [comment]
@henhuy I think this is a good idea! I think the urls could even be in german actually, since most users will probably use the german version.

**Comment by henhuy** [comment]
- "welcome/"                          
- "route/"
- "display_route/"
- "comparison/"
- "environment/"
- "dashboard/"
- "quiz/<str:category>/"
- "answer/"
- "tour/"
- "finished/<str:category>/"                
- "questions_as_text/"                    
- "legal/"
- "accept_privacy_policy/"
- "send_posthog_event/"
- "get_comparison_chart/"
