### ISSUE TITLE
Stations component

### ISSUE THREAD

**Issue by henhuy** [rl-institut/E_Metrobus#4]
Build stations component to select two stations. Stations in between selection shall be highlighted.

TODOS:

- [x] Layout 
- [x] Functionality
- [x] Django component
- [x] Layout error message and button (see #17)

**Comment by bmlancien** [comment]
@mdrli Can you implement the button footer design like on Figma ('Strecke bestätigen')? Use position fixed and work on branch fe/route.

@henhuy I thought again about the interaction on this page and you are probably right, it should be possible for the user to unselect selected stations at any moment (and not first arrival and THEN departure station). If it takes too much time to change the JS code now, we could do this change later once the app is complete and we have more time. What do you think?

**Comment by henhuy** [comment]
Button is added and is showed only if exactly 2 stations are selected

**Comment by henhuy** [comment]
We also need text showing up if no or one stations is selected:
- "Wo bist du eingestiegen"
- "Wo bist du ausgestiegen"

@mdrli or @bmlancien : Could you add this to the widget?
Afterwards I can hide/unhide it via stations.js...

**Comment by bmlancien** [comment]
@henhuy Questions added
