### ISSUE TITLE
Keyboard changes app to landscape mode (on mobile)

### ISSUE THREAD

**Issue by henhuy** [rl-institut/E_Metrobus#405]
If you want to give feedback, landscape view if shown as soon as mobile keyboard gets active. No feedback possible this way!

**Comment by henhuy** [comment]
Important! Ideas? @bmlancien

**Comment by henhuy** [comment]
Turn off landscape view if feedback/bug is shown (by JS)?

**Comment by bmlancien** [comment]
> Turn off landscape view if feedback/bug is shown (by JS)?

Okay!
