### ISSUE TITLE
Desktop LP too large on some screens

### ISSUE THREAD

**Issue by bmlancien** [rl-institut/E_Metrobus#419]

**Comment by henhuy** [comment]
Saw that on NPs PC.
You can see it yourself, if you shrink your browser window.
But I think it is okay - looks good for me too?!

**Comment by bmlancien** [comment]
Ok, if it's because the screen/window is small, I don't think I need to change this. I will ask again.

**Comment by bmlancien** [comment]
I just asked. We can close that issue.
