### ISSUE TITLE
Remove "see more" button on answer page

### ISSUE THREAD

**Issue by bmlancien** [rl-institut/E_Metrobus#47]
Issue: The user has to tap each time on "see more" button to see the full answer

Suggestion: Remove the "see more" button and display the whole answer at once. In that case the short answer should be visually more important than the long answer text to keep a hierarchy of importance

**Comment by henhuy** [comment]
Hi @mdrli, 
> the short answer should be visually more important than the long answer

is still missing - can you add styling for short answer? thx

**Comment by mdrli** [comment]
Sure @henhuy ,
is there a style I should use?

**Comment by bmlancien** [comment]
@mdrli 

> is there a style I should use?

Can you try with font-weight 700 for the short answer and 300 for the longer answer?

![answer](https://user-images.githubusercontent.com/33999424/74152848-789d0c00-4c0f-11ea-8070-c8f553b15ec4.png)
