### ISSUE TITLE
https in the URL

### ISSUE THREAD

**Issue by bmlancien** [rl-institut/E_Metrobus#471]
@henhuy Maybe this is not an issue. Now we have to write `https://` in the search bar to open the link. Will it be necessary once the final web address is accessible? If yes, it would be nice not to have to do this. Because users would probably not understand that they have to write it in order to open the page. If no, you can just close that issue :)

**Comment by henhuy** [comment]
For original page, there is a redirect to https.
Did not activate it for dev app...
