### ISSUE TITLE
Some EN translations are not displayed

### ISSUE THREAD

**Issue by bmlancien** [rl-institut/E_Metrobus#473]
I don't know why the followings don't display the translation correctly:

- [x] Chart
- [x] Data table
- [x] Sources
- [x] Footer
- [x] Slogan (share app)
- [x] Top nav (category names)
- [x] Some questions in environment category
- [x] Third question short answer (policy category)
- [x] First question short answer (me category)
- [x] Third question (me category)

There is also some new text to translate:
- [x] BVG partner text on LP
- [x] TUB partner text on LP

**Comment by henhuy** [comment]
Hey @ciaradunks,
I just compiled `translation/2020-07-30` branch to our dev server.
I already solved some of the problems above.
But there are some translations missing.
I currently don't know the status of your translations? Are still working on it? What are your capacities?
Thanks
