### ISSUE TITLE
Whatsapp image is not displayed on share page (Safari emulator)

### ISSUE THREAD

**Issue by bmlancien** [rl-institut/E_Metrobus#476]
![Bildschirmfoto vom 2020-08-05 14-36-00](https://user-images.githubusercontent.com/33999424/89414508-cc099600-d72a-11ea-9d55-ec998ba2639f.png)

**Comment by bmlancien** [comment]
@timroepcke Can you check if you have this issue (using Safari)? This is from an emulator, so I don't know how close to reality it is.

**Comment by henhuy** [comment]
Image is broken! (Don't know why...)
Cannot open it on my local machine...
Can you find/upload another one?
