### ISSUE TITLE
Score animation is missing

### ISSUE THREAD

**Issue by bmlancien** [rl-institut/E_Metrobus#52]
PRIORITY 2

- [x] animate points won after answering the question:
- move from 20% bottom to 20% top
- max 1 sec
- fade in at beginning and fade out at end
- [ ] animate total score on top:
- short increase in size of star and score
- max 0.5 sec

**Comment by henhuy** [comment]
By now, user also gets some points even if answer is wrong. Should we add score animation to wrong answer page too (maybe smaller)?

**Comment by bmlancien** [comment]
I'm not sure about that. I would leave it for now and we can discuss this again after user testings.

**Comment by henhuy** [comment]
@mdrli already made a small start for a wrong answer - but we can easily turn it off, if necessary.

**Comment by bmlancien** [comment]
Sure, let's keep it first

**Comment by mdrli** [comment]
Should the total score animation, have the same increase in size as the right answer animation?

**Comment by bmlancien** [comment]
> Should the total score animation, have the same increase in size as the right answer animation?

It should be a bit smaller, because it it on the top navigation and there is not much space available
