### ISSUE TITLE
Route results CO2

### ISSUE THREAD

**Issue by henhuy** [rl-institut/E_Metrobus#6]
Show CO2 results for different mobility scenarios

TODOS:

- [x] Layout
- [x] Show comparison
- [ ] Get and show CO2 numbers
- [x] Animation
- [x] Backend implementation

**Comment by bmlancien** [comment]
@henhuy i added new icons for the comparison page in frontend branch. They shouldn't be blurred anymore. Also, I added gray icons. I think it is visually easier to understand if the e-bus icon stays black and the other get the gray color. See #51 I added a screenshot of what I mean.

**Comment by henhuy** [comment]
@bmlancien - nice! But where did you add it? Cannot find related PR.

**Comment by bmlancien** [comment]
@henhuy sorry, I didn't mention it. Because I thought that adding icons was something more general, I did it in the frontend branch and so I was not thinking of doing a PR for that branch. Should I do a PR nevertheless?

**Comment by henhuy** [comment]
no - it's okay! thx

**Comment by henhuy** [comment]
new icons are added
