### ISSUE TITLE
Show project information on desktop page

### ISSUE THREAD

**Issue by henhuy** [rl-institut/E_Metrobus#60]
Show following things on "desktop page", instead of hint to use mobile app
- [x] Mobile app advertisement
- [x] Project info
- [x] Add correct QR code

**Comment by henhuy** [comment]
Hey @mdrli , did you already styled a nice QR code? (maybe with BVG logo inside?)
URL should be: https://e-metrobus.berlin

**Comment by mdrli** [comment]
What about this? @henhuy Is it okay or should it be more fancy or something?

![qr-code](https://user-images.githubusercontent.com/56251368/74422776-6c06f680-4e4f-11ea-94a2-0cfb427c6b70.png)

**Comment by henhuy** [comment]
very nice! @bmlancien ?

**Comment by mdrli** [comment]
Could you take a look on the implemented QR-Code? The Logo seems to be  a bit blurred. @henhuy

**Comment by bmlancien** [comment]
> Could you take a look on the implemented QR-Code? The Logo seems to be a bit blurred. @henhuy @bmlancien

@mdrli It looks fine to me, we can keep it like this

**Comment by henhuy** [comment]
> Could you take a look on the implemented QR-Code? The Logo seems to be a bit blurred. @henhuy @bmlancien

For me it is also blurred! As the logo is only inserted png, it doesn't scale well.
Two options:
- Logo with higher dimension
- Increase QR code image (I think it could be more present)

**Comment by mdrli** [comment]
@henhuy Do we have a scaleable logo? Or one with higher dimension? Increasing the Image doesn't do it.

**Comment by henhuy** [comment]
> @henhuy Do we have a scaleable logo? Or one with higher dimension? Increasing the Image doesn't do it.

Don't know. @bmlancien ?

**Comment by bmlancien** [comment]
I don't know. What is blurred exactly? The BVG logo or the QR-code?

**Comment by henhuy** [comment]
> I don't know. What is blurred exactly? The BVG logo or the QR-code?

The **BVG Logo**  is blurred on big screen, as the whole QR-Code is shown very small

**Comment by bmlancien** [comment]
@mdrli have you tried with svg pictures?

https://en.wikipedia.org/wiki/Berliner_Verkehrsbetriebe?uselang=de#/media/File:Bvg-logo.svg

**Comment by mdrli** [comment]
I have tried it. Also I increased the whole QR-Code a bit. I think that this might be okay now. @bmlancien
