### ISSUE TITLE
Quiz Category Finished page is missing

### ISSUE THREAD

**Issue by bmlancien** [rl-institut/E_Metrobus#62]
When the user answers all the questions of a category, she should win extra points and be able to see it. A page "Congrats, you answered all the questions of category X" should exist (about 2 seconds long before display none?)

**Comment by henhuy** [comment]
@mdrli designed layout for category finished page:
![grafik](https://user-images.githubusercontent.com/17476051/72978370-a04e4080-3dd6-11ea-8f11-f8f6efd93cbd.png)
What do you think @bmlancien ?
