### ISSUE TITLE
Navigation menu

### ISSUE THREAD

**Issue by henhuy** [rl-institut/E_Metrobus#7]
Implement menu to switch between:
- contact/dgstvo/etc.
- route selection
- text answers to all questions
- dashboard

TODOS:

- [x] Layout 
- [x] backend template for menu
- [x] mark current page
- [x] CSS white, gray, black (selected)

**Comment by bmlancien** [comment]
#18

**Comment by bmlancien** [comment]
@henhuy I have changed the icon 'pin' to 'leaf', since a pin icon was not fitting to the concept of the content that will be included in that page (CO2 results)
