### ISSUE TITLE
Top nav on onboarding pages is not leading to /route

### ISSUE THREAD

**Issue by bmlancien** [rl-institut/E_Metrobus#72]
On /display_route and /comparison, the arrow on the left (top navigation) should not lead to the dashboard but to /route instead. The idea is that user can change the route if she wants before accessing the dashboard (e.g. after realizing that the chosen route was not the right one)

![comparison](https://user-images.githubusercontent.com/33999424/73445902-0baa8c00-435c-11ea-962a-68dd5eba17ba.png)

**Comment by henhuy** [comment]
Removed link in top bar for display_route and comparison page in favour of text "< Strecke ändern" in page layout. Design of icon and text has to be adapted in file `templates/includes/cange_route.html`.
