### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by henhuy** [rl-institut/E_Metrobus#8]
Implement dashboard

TODOS:

- [x] Layout
- [ ] Show score
- [ ] Show categories with progress

**Comment by bmlancien** [comment]
@henhuy Instead of black, could you use #17BEBB as a color for the svg ellipses used as progress bars? Black can still be used when the progress bar is full though.

![Dashboard (2)](https://user-images.githubusercontent.com/33999424/68861937-d55e5880-06ec-11ea-9df3-1290d05b4f2d.png)
